APP_SUMMARY = {
    "name": "RoomRadar",
    "tagline": "Cross-city rental search, qualification, and outreach in one workflow.",
    "stats": [
        {"label": "Cities", "value": "3"},
        {"label": "Profiles", "value": "12"},
        {"label": "Qualified", "value": "41"},
        {"label": "Time Saved", "value": "~11h"},
    ],
}


DEFAULT_CITY = "singapore"


COMMON_OPTIONS = {
    "move_in": ["Immediately", "Within 2 weeks", "Late April or 1 May", "Mid May", "June"],
    "lease_term": ["6 months", "12 months", "18 months", "Flexible"],
    "room_type": ["Master room only", "Master preferred", "Any room type"],
    "bathroom": ["Attached bathroom only", "Private bathroom preferred", "Any bathroom setup"],
    "bathroom_sharing": ["Private bathroom only", "Shared with 1 person max", "Any bathroom arrangement"],
    "cooking": ["Normal cooking required", "Light cooking acceptable", "No preference"],
    "kitchen_access": ["Full kitchen access required", "Stove access required", "Light kitchen access acceptable", "No preference"],
    "visitors": ["Occasional overnight guests required", "Visitors okay, overnight preferred", "No preference"],
    "owner_stay": ["No owner stay", "Owner stay okay"],
    "furnishing": ["Fully furnished", "Partially furnished", "No preference"],
    "gender_rule": ["No gender restrictions", "Male only okay", "Female only okay"],
    "aircon": ["Aircon required", "Fan okay", "No preference"],
    "laundry": ["Washer access required", "Washer and dryer preferred", "No preference"],
    "wifi": ["Wi-Fi included", "Wi-Fi preferred", "No preference"],
    "household_size": ["Max 2 other occupants", "Max 4 other occupants", "No preference"],
    "nationality_rule": ["No nationality restrictions", "Open to nationality preference"],
    "message_tone": ["Direct and professional", "Warm and friendly", "Short and practical"],
}


CITIES = {
    "singapore": {
        "name": "Singapore",
        "currency_symbol": "S$",
        "budget_step": 50,
        "source_sites": ["PropertyGuru", "99.co", "Carousell Property"],
        "source_note": "Room and condo inventory is usually strongest on PropertyGuru and 99.co.",
        "transit_label": "Walk to MRT",
        "transit_options": ["5 mins max", "10 mins max", "15 mins max", "No preference"],
        "property_type_options": ["HDB only", "Condo only", "Landed only", "Any property type"],
        "area_groups": {
            "East": ["Eunos", "Kembangan", "Bedok", "Tanah Merah", "Simei", "Tampines", "Pasir Ris"],
            "City Fringe East": ["Aljunied", "Paya Lebar", "MacPherson", "Tai Seng", "Dakota", "Mountbatten", "Geylang"],
            "Marine Parade Belt": ["Marine Parade", "Tanjong Katong", "Marine Terrace", "Siglap", "Bayshore"],
            "Central": ["Bugis", "City Hall", "Promenade", "Dhoby Ghaut", "Somerset", "Orchard", "Newton"],
            "West": ["Queenstown", "Redhill", "Tiong Bahru", "Buona Vista", "Clementi", "Jurong East"],
        },
        "extra_filters": [
            {"key": "pass_type", "label": "Pass / visa type", "type": "select", "options": ["Employment Pass", "S Pass", "Student Pass", "No preference"]},
            {"key": "one_pax_only", "label": "1 pax only listings", "type": "select", "options": ["Allow", "Reject"]},
        ],
        "default_profile": {
            "budget_min": 1700,
            "budget_max": 2000,
            "areas": ["Aljunied", "Eunos", "Kembangan", "Tanah Merah", "Siglap", "Marine Parade"],
            "move_in": "Late April or 1 May",
            "lease_term": "12 months",
            "room_type": "Master room only",
            "bathroom": "Attached bathroom only",
            "bathroom_sharing": "Private bathroom only",
            "cooking": "Normal cooking required",
            "kitchen_access": "Full kitchen access required",
            "visitors": "Occasional overnight guests required",
            "owner_stay": "No owner stay",
            "property_type": "Any property type",
            "furnishing": "Fully furnished",
            "gender_rule": "No gender restrictions",
            "aircon": "Aircon required",
            "laundry": "Washer access required",
            "wifi": "Wi-Fi included",
            "household_size": "Max 4 other occupants",
            "nationality_rule": "No nationality restrictions",
            "transit_access": "10 mins max",
            "pass_type": "Employment Pass",
            "one_pax_only": "Allow",
            "max_listing_age_days": 7,
            "must_include_keywords": "ensuite, attached bath, private bathroom",
            "blocked_keywords": "shared bathroom, owner stays, microwave only, no overnight",
            "notes": "Shared bathroom should be rejected. 1 pax only can still be considered.",
            "contact_name": "Ismail",
            "occupation": "Turkish consultant on an Employment Pass",
            "living_style": "alone most of the time",
            "visitor_context": "my girlfriend may occasionally stay over on some weekends",
            "cooking_style": "cook proper meals regularly",
            "message_tone": "Direct and professional",
            "custom_message_notes": "Mention the listing link and ask if the arrangement works.",
        },
    },
    "dubai": {
        "name": "Dubai",
        "currency_symbol": "AED ",
        "budget_step": 250,
        "source_sites": ["Property Finder", "Bayut", "Dubizzle"],
        "source_note": "Property Finder and Bayut are strong for managed inventory; Dubizzle is useful for owner-side stock.",
        "transit_label": "Walk to Metro / Tram",
        "transit_options": ["5 mins max", "10 mins max", "15 mins max", "No preference"],
        "property_type_options": ["Apartment only", "Villa only", "Townhouse okay", "Any property type"],
        "area_groups": {
            "Marina Corridor": ["Dubai Marina", "JLT", "JBR", "Dubai Harbour", "Dubai Media City"],
            "Central": ["Business Bay", "Downtown Dubai", "DIFC", "Al Satwa", "City Walk"],
            "West / New Dubai": ["JVC", "JVT", "Al Barsha", "Dubai Hills", "Motor City", "Arjan"],
            "Budget-Friendly": ["Discovery Gardens", "Al Nahda", "International City", "Dubai Silicon Oasis"],
        },
        "extra_filters": [
            {"key": "chiller", "label": "Chiller", "type": "select", "options": ["Included", "Not required", "No preference"]},
            {"key": "dewa", "label": "DEWA / utilities", "type": "select", "options": ["Included preferred", "No preference"]},
            {"key": "parking", "label": "Parking", "type": "select", "options": ["Required", "Preferred", "No preference"]},
        ],
        "default_profile": {
            "budget_min": 3500,
            "budget_max": 6000,
            "areas": ["Dubai Marina", "JLT", "Business Bay", "JVC"],
            "move_in": "Within 2 weeks",
            "lease_term": "12 months",
            "room_type": "Master preferred",
            "bathroom": "Attached bathroom only",
            "bathroom_sharing": "Private bathroom only",
            "cooking": "Normal cooking required",
            "kitchen_access": "Full kitchen access required",
            "visitors": "No preference",
            "owner_stay": "No owner stay",
            "property_type": "Apartment only",
            "furnishing": "Fully furnished",
            "gender_rule": "No gender restrictions",
            "aircon": "Aircon required",
            "laundry": "Washer access required",
            "wifi": "Wi-Fi preferred",
            "household_size": "Max 2 other occupants",
            "nationality_rule": "No nationality restrictions",
            "transit_access": "10 mins max",
            "chiller": "Included",
            "dewa": "Included preferred",
            "parking": "No preference",
            "max_listing_age_days": 10,
            "must_include_keywords": "ensuite, attached bathroom, furnished",
            "blocked_keywords": "partition, bed space, no guests, no cooking",
            "notes": "Prefer proper buildings near Metro with no partition setup.",
            "contact_name": "RoomRadar user",
            "occupation": "working professional relocating to Dubai",
            "living_style": "alone",
            "visitor_context": "I may occasionally have guests",
            "cooking_style": "cook regularly",
            "message_tone": "Warm and friendly",
            "custom_message_notes": "Ask about utilities and tower rules if unclear.",
        },
    },
    "istanbul": {
        "name": "Istanbul",
        "currency_symbol": "TRY ",
        "budget_step": 1000,
        "source_sites": ["Sahibinden", "Hepsiemlak", "Emlakjet"],
        "source_note": "Sahibinden is broadest for raw inventory; Hepsiemlak and Emlakjet help with agency-heavy supply.",
        "transit_label": "Walk to Metro / Metrobüs / Marmaray",
        "transit_options": ["5 dk max", "10 dk max", "15 dk max", "Farketmez"],
        "property_type_options": ["Apartment only", "Residence only", "Site içi preferred", "Any property type"],
        "area_groups": {
            "European Core": ["Sisli", "Mecidiyekoy", "Gayrettepe", "Besiktas", "Levent", "Maslak"],
            "Metrobüs Belt": ["Zincirlikuyu", "Cevizlibag", "Merter", "Avcilar", "Beylikduzu", "Sogutlucesme"],
            "Anatolian": ["Kadikoy", "Acibadem", "Goztepe", "Kozyatagi", "Atasehir", "Uskudar"],
            "Lifestyle": ["Nisantasi", "Cihangir", "Bomonti", "Etiler", "Moda", "Fenerbahce"],
        },
        "extra_filters": [
            {"key": "metrobus_access", "label": "Metrobüs access", "type": "select", "options": ["Required", "Preferred", "Not needed"]},
            {"key": "marmaray_access", "label": "Marmaray access", "type": "select", "options": ["Preferred", "Not needed"]},
            {"key": "earthquake_pref", "label": "Building preference", "type": "select", "options": ["Newer / earthquake-conscious building", "No preference"]},
            {"key": "site_ici", "label": "Site içi", "type": "select", "options": ["Preferred", "Not required"]},
        ],
        "default_profile": {
            "budget_min": 25000,
            "budget_max": 45000,
            "areas": ["Mecidiyekoy", "Gayrettepe", "Sisli", "Kadikoy", "Kozyatagi"],
            "move_in": "Within 2 weeks",
            "lease_term": "12 months",
            "room_type": "Any room type",
            "bathroom": "Private bathroom preferred",
            "bathroom_sharing": "Shared with 1 person max",
            "cooking": "Normal cooking required",
            "kitchen_access": "Full kitchen access required",
            "visitors": "No preference",
            "owner_stay": "No owner stay",
            "property_type": "Apartment only",
            "furnishing": "Fully furnished",
            "gender_rule": "No gender restrictions",
            "aircon": "No preference",
            "laundry": "Washer access required",
            "wifi": "Wi-Fi preferred",
            "household_size": "Max 4 other occupants",
            "nationality_rule": "No nationality restrictions",
            "transit_access": "10 dk max",
            "metrobus_access": "Preferred",
            "marmaray_access": "Not needed",
            "earthquake_pref": "Newer / earthquake-conscious building",
            "site_ici": "Preferred",
            "max_listing_age_days": 10,
            "must_include_keywords": "metrobus, metro, furnished",
            "blocked_keywords": "depozitosuz dolandirici, only female, shared saloon",
            "notes": "Transit and building quality matter more here than owner messaging speed.",
            "contact_name": "RoomRadar user",
            "occupation": "professional moving within Istanbul",
            "living_style": "mostly alone",
            "visitor_context": "I may occasionally host friends or family",
            "cooking_style": "cook at home regularly",
            "message_tone": "Short and practical",
            "custom_message_notes": "Ask about aidat, transit access, and building age.",
        },
    },
}


PROFILES = [
    {"id": "ismail-singapore", "city": "singapore", "name": "Ismail - East Singapore", **CITIES["singapore"]["default_profile"]},
    {"id": "dubai-marina", "city": "dubai", "name": "Dubai - Marina Search", **CITIES["dubai"]["default_profile"]},
    {"id": "istanbul-commute", "city": "istanbul", "name": "Istanbul - Commute Friendly", **CITIES["istanbul"]["default_profile"]},
]


LISTINGS = [
    {
        "id": "500091644",
        "profile_id": "ismail-singapore",
        "city": "singapore",
        "status": "qualified",
        "title": "99B Circuit Road",
        "price": "S$1,800/mo",
        "posted": "Listed on 28 Mar 2026",
        "agent": "Nicholas Feng",
        "phone": "+65 8511 0090",
        "url": "https://www.propertyguru.com.sg/listing/hdb-for-rent-99b-circuit-road-500091644",
        "summary": "Master bedroom with ensuite bathroom right beside MRT.",
        "positive": ["ensuite", "master bedroom", "private bathroom"],
        "risks": [],
        "reasons": [],
        "draft": "Hi Nicholas Feng, I'm Ismail, a Turkish consultant on an Employment Pass. Listing: https://www.propertyguru.com.sg/listing/hdb-for-rent-99b-circuit-road-500091644",
    },
    {
        "id": "16056613",
        "profile_id": "ismail-singapore",
        "city": "singapore",
        "status": "rejected",
        "title": "Atrium Residences",
        "price": "S$1,500/mo",
        "posted": "Listed on 26 Mar 2026",
        "agent": "Valerie Yong",
        "phone": "+65 9792 3413",
        "url": "https://www.propertyguru.com.sg/listing/for-rent-atrium-residences-16056613",
        "summary": "Fully furnished huge common bedroom.",
        "positive": ["close to MRT"],
        "risks": ["shared bathroom"],
        "reasons": ["price_below_limit", "banned:shared bathroom"],
        "draft": "Hi Valerie Yong, I'm reaching out about your listing: https://www.propertyguru.com.sg/listing/for-rent-atrium-residences-16056613",
    },
    {
        "id": "dubai-001",
        "profile_id": "dubai-marina",
        "city": "dubai",
        "status": "qualified",
        "title": "Marina Gate Room",
        "price": "AED 5,200/mo",
        "posted": "Listed on 29 Mar 2026",
        "agent": "Amina Rahman",
        "phone": "+971 55 110 8829",
        "url": "https://www.propertyfinder.ae/en/plp/rent/apartment-for-rent-dubai-marina-gate-demo",
        "summary": "Ensuite room in Dubai Marina, 7 minutes to Metro, chiller included.",
        "positive": ["metro access", "ensuite", "chiller included"],
        "risks": [],
        "reasons": [],
        "draft": "Hi Amina Rahman, I'm interested in your Dubai Marina listing: https://www.propertyfinder.ae/en/plp/rent/apartment-for-rent-dubai-marina-gate-demo",
    },
    {
        "id": "dubai-002",
        "profile_id": "dubai-marina",
        "city": "dubai",
        "status": "risky",
        "title": "JVC Shared Apartment",
        "price": "AED 4,100/mo",
        "posted": "Listed on 27 Mar 2026",
        "agent": "Farhan Malik",
        "phone": "+971 50 222 3344",
        "url": "https://www.bayut.com/to-rent/property/dubai/jvc-demo",
        "summary": "Large room with balcony in JVC. Good kitchen but transport is less clear.",
        "positive": ["full kitchen", "furnished"],
        "risks": ["metro distance unclear"],
        "reasons": ["manual review recommended"],
        "draft": "Hi Farhan Malik, could you confirm the exact transit access and guest rules for this listing? https://www.bayut.com/to-rent/property/dubai/jvc-demo",
    },
    {
        "id": "ist-001",
        "profile_id": "istanbul-commute",
        "city": "istanbul",
        "status": "qualified",
        "title": "Mecidiyekoy 1+1 Residence",
        "price": "TRY 39,000/mo",
        "posted": "Listed on 29 Mar 2026",
        "agent": "Ece Demir",
        "phone": "+90 533 000 1122",
        "url": "https://www.sahibinden.com/ilan/emlak-konut-kiralik-mecidiyekoy-1-plus-1-demo",
        "summary": "Furnished residence near Metro and Metrobus, newer building, site amenities.",
        "positive": ["metrobus nearby", "new building", "site ici"],
        "risks": [],
        "reasons": [],
        "draft": "Merhaba Ece Hanim, ilaninizi gordum ve detaylarla ilgileniyorum: https://www.sahibinden.com/ilan/emlak-konut-kiralik-mecidiyekoy-1-plus-1-demo",
    },
    {
        "id": "ist-002",
        "profile_id": "istanbul-commute",
        "city": "istanbul",
        "status": "rejected",
        "title": "Kadikoy Shared Flat",
        "price": "TRY 22,000/mo",
        "posted": "Listed on 25 Mar 2026",
        "agent": "Mert Can",
        "phone": "+90 532 333 4455",
        "url": "https://www.hepsiemlak.com/istanbul-kadikoy-kiralik-oda-demo",
        "summary": "Affordable room but bathroom sharing and older building are concerns.",
        "positive": ["good neighborhood"],
        "risks": ["older building", "shared bathroom"],
        "reasons": ["shared bathroom", "building quality mismatch"],
        "draft": "Merhaba, paylasimli banyo ve bina durumu hakkinda net bilgi rica edecektim: https://www.hepsiemlak.com/istanbul-kadikoy-kiralik-oda-demo",
    },
]
